name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-java@v6
      with:
        java-version: openjdk@1.9.0
    - uses: stCarolas/setup-maven@v3
      with:
        maven-version: 3.5.4
    - name: Build with Maven
      run: mvn -B clean compile test --file pom.xml
