name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: joschi/setup-jdk@v1
      with:
        java-version: '8'
        architecture: 'x64'
    - uses: stCarolas/setup-maven@v3
      with:
        maven-version: 3.5.4
    - name: Build with Maven
      run: mvn -B clean compile test --file pom.xml
